name: Build and Release Fat Jar

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Cache Gradle dependencies
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Grant execute permissions for Gradle Wrapper
    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    # Build Fat Jar
    - name: Build Fat Jar
      run: ./gradlew build fatJar

    # Verify the Fat Jar exists
    - name: List app/build/libs directory
      run: ls -la app/build/libs/

    # Upload Fat Jar as an artifact (optional for debugging)
    - name: Upload Fat Jar Artifact
      uses: actions/upload-artifact@v3
      with:
        name: fatJar
        path: app/build/libs/CompetitiveCounting.jar

    # Publish the Fat Jar as a GitHub release
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ github.run_number }} # Auto-generate a version tag
        release_name: "Release ${{ github.run_number }}"
        body: |
          This release contains the latest build of the Fat Jar.
        files: app/build/libs/CompetitiveCounting.jar
        draft: false
        prerelease: false
