name: Build Fat Jar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Cache Gradle dependencies
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Grant execute permissions for Gradle Wrapper
    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    # Build the fat JAR
    - name: Build Fat Jar
      run: ./gradlew fatJar

    # Save the artifact (optional)
    - name: Upload Fat Jar
      uses: actions/upload-artifact@v3
      with:
        name: fatJar
        path: build/libs/*.jar
